### ISSUE TITLE
Remove the CAN bus interface configuration window, configure the interface from the main GUI after the application is started

### ISSUE THREAD

**Issue by pavel-kirienko** [UAVCAN/gui_tool#13]

**Comment by j3qq4hch** [comment]
Why would you do that?! Current realisation seems totally ok

**Comment by pavel-kirienko** [comment]
Several reasons:

1. It doesn't allow one to use the GUI tool in offline mode, e.g. for the purposes of reviewing old traffic dumps.
2. It is not possible to switch the interface without restarting the application.
3. @olliw42 has rightfully reported that if the interface dies, the application must be restarted, since there is not way to tell it to use another interface without shutting it down.

**Comment by pavel-kirienko** [comment]
Closing because this application will soon be superseded by Yukon: https://forum.uavcan.org/t/gui-tool-next-generation/229
