### ISSUE TITLE
CAN serial ports are renamed to "n/a" (by Qt?!)

### ISSUE THREAD

**Issue by mkeeter** [UAVCAN/gui_tool#21]
Running on Mac OS 10.12.

For some reason, multiple ports are named "n/a", so only one shows up in the initial setup window.  Doing a little bit of debugging, I tracked it down to the Qt import (?!?).  Here's a minimal reproducible case:

```
import serial.tools.list_ports

for port, name, _ in serial.tools.list_ports.comports():
    print(port, name)

print("----------")

from PyQt5.QtCore import Qt
for port, name, _ in serial.tools.list_ports.comports():
    print(port, name)
```

On my machine, this prints
```
/dev/cu.Bluetooth-Incoming-Port n/a
/dev/cu.usbserial-LW1L5G7Q CANUSB - CANUSB
/dev/cu.usbmodem7AB068B1 Black Magic Probe
/dev/cu.usbmodem7AB068B3 Black Magic Probe
----------
/dev/cu.Bluetooth-Incoming-Port n/a
/dev/cu.usbserial-LW1L5G7Q n/a
/dev/cu.usbmodem7AB068B1 Black Magic Probe
/dev/cu.usbmodem7AB068B3 Black Magic Probe
```

This is a very unexpected interaction.  I tried to work around by rearranging so that `list_ifaces` is defined before any Qt imports, but any subsequent Qt imports causes the renaming to happen.

**Comment by mkeeter** [comment]
One suggested fix: it looks like `PyQt5.QtSerialPort.QSerialPortInfo.availablePorts()` performs a similar function.  This would let us remove the `serial` dependency completely (and we could even consolidate the Linux / other platform code, since Qt is pretty good about cross-platform behavior).

**Comment by pavel-kirienko** [comment]
Thanks, Matt. Perhaps you could send a pull request with your proposed fix? I have no way of testing it on Mac myself, I'm on Linux.
