### ISSUE TITLE
Plotter filter for uavcan.protocol.debug.KeyValue

### ISSUE THREAD

**Issue by j3qq4hch** [UAVCAN/gui_tool#26]
If you try to add filter for `uavcan.protocol.debug.KeyValue` message and filter out only messages with specified key you have to use filter:
`msg.key.decode() == 'some_key'`
instead of
`msg.key == 'some_key'`

**Comment by pavel-kirienko** [comment]
Moved over to the linked issue at PyUAVCAN, closing
