### ISSUE TITLE
Launch GUI tool macOS

### ISSUE THREAD

**Issue by Alexivia** [UAVCAN/gui_tool#29]
Hi,

I succeeded in installing the GUI tool via the MacPorts option given on your documentation, and I can see via `pip freeze` that it is indeed installed. However, I can't seem to figure out how to launch it. It is probably very simple, but I don't know how...

Thank you for your time.

**Comment by pavel-kirienko** [comment]
You should be able to launch it simply by running `uavcan_gui_tool` on the command line. Since you're on Mac (I'm on Linux), perhaps you could somehow modify the installation instructions to make the icon appear in the app launcher?

**Comment by Alexivia** [comment]
Thank you Pavel for your response, but unfortunately that is not true. The binary is located at `/opt/local/Library/Frameworks/Python.framework/Versions/3.6/bin/uavcan_gui_tool`, and since it does not make part of the standard environment variables, I had to add an alias to it.
