### ISSUE TITLE
Windows installer failure

### ISSUE THREAD

**Issue by j3qq4hch** [UAVCAN/gui_tool#3]
When i try to launch GUI tool 0.8 on my win7 pc, i get this: 
![2016-11-02 10 17 48](https://cloud.githubusercontent.com/assets/9300016/19920231/86743414-a0e8-11e6-8ce1-3560db23f24f.png)

**Comment by pavel-kirienko** [comment]
Should be fixed in the updated installer: https://files.zubax.com/products/org.uavcan.gui_tool/uavcan_gui_tool-0.8.0-win32.signed.msi

Please reopen if this didn't help
