### ISSUE TITLE
PyQt5/QtCore.so: undefined symbol: “PySlice_AdjustIndices”

### ISSUE THREAD

**Issue by thirtytwobits** [UAVCAN/gui_tool#31]
If anybody is seeing PyQt5/QtCore.so: undefined symbol: “PySlice_AdjustIndices” when running gui_tool see this issue -> https://www.riverbankcomputing.com/pipermail/pyqt/2018-July/040511.html

This is not a bug in gui_tool but in PyQt5

**Comment by thirtytwobits** [comment]
A suggested workaround:
```
sudo pip3 install -Iv PyQt5==5.10.1
```

**Comment by pavel-kirienko** [comment]
Should we update `setup.py`?

**Comment by thirtytwobits** [comment]
Probably. Unfortunately I'm not able to contribute to this repository. Sorry.

**Comment by pavel-kirienko** [comment]
Closing as obsolete as this bug in PyQt was fixed long ago.
