### ISSUE TITLE
Add support to select Socket can interfaces

### ISSUE THREAD

**Issue by irieblue** [UAVCAN/gui_tool#33]
I have an ubuntu system where the CAN interface appears as a network interface - can0 . The driver plumbs this as a socket can device and not a traditional UART/Serial device.

It would be helpful to have the gui_tool communicate over socket can on systems where that is the hardware interface to the UAVCAN device.

It would make for a good sample application/code on how to use UAVCAN programmatically over Socket can.

**Comment by kjetilkjeka** [comment]
The gui tool works over socketcan. When `ifconfig` shows a socketcan interface the gui tool will also have an alternative for chosing that interface. If this doesn't work, something is off at your end.

Can you confirm that `ifconfig` shows the socketcan interface?

Perhaps you also should set up a virtual can interface and see if it works with it?

**Comment by pavel-kirienko** [comment]
Closing because as Kjetil said, SocketCAN is already supported.
