### ISSUE TITLE
Creating panels with package that is not in gui tool python environment 

### ISSUE THREAD

**Issue by rubengr** [UAVCAN/gui_tool#36]
It's possible to add new packages in environment of pre-built gui tool? We need to create a new panel in gui tool that needs other package that is not used by uavcan gui tool.
Thanks
Rúben Rodrigues

**Comment by pavel-kirienko** [comment]
Sure, you can just list your packages here: https://github.com/UAVCAN/gui_tool/blob/c657980b086214af241c908948ea32a2c95aab23/setup.py#L52-L68

If you want to add your packages to an already installed (deployed) application, just drop them into the installation folder.
