### ISSUE TITLE
Linux launch

### ISSUE THREAD

**Issue by j3qq4hch** [UAVCAN/gui_tool#4]
When I try to launch GUI tool on Linux using icon in menu, it launches and asks me what can adapter I would like to use. But then it can't get access to my adapter and fails.
So I have to launch it using console like this
sudo uavcan_gui_tool 

But what is the point of having pretty icon in the menu then?

**Comment by pavel-kirienko** [comment]
You need to fix access permissions for your adapter, as described here https://docs.zubax.com/usb#Configuring_permissions_on_Linux
