### ISSUE TITLE
Logger illumination

### ISSUE THREAD

**Issue by PrincePepper** [UAVCAN/gui_tool#54]
How do you like the idea of making code highlighting for a more beautiful display?  

Now:
![SharedScreenshot](https://user-images.githubusercontent.com/43268369/128533970-7e7022ca-4923-4030-9f7b-660ea801b14e.jpg)
My idea:
![image](https://user-images.githubusercontent.com/43268369/128535035-38ed384d-c015-44a2-b119-0ac760b5de2b.png)

Sample code:
` logger.info('Param get/set response: '+LoggerCustomColor.BOLD+'%s'+LoggerCustomColor.ENDC, e.response)`

Here is the class itself `LoggerCustomColor`:
```
class LoggerCustomColor:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKCYAN = '\033[96m'
    OKGREEN = '\033[92m'

    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'
```

**Comment by pavel-kirienko** [comment]
This will break if stderr is not connected to a tty or if the terminal is not vt100-compatible. There are libraries out there like coloredlogs or colorama which automate this properly but I am not sure their addition is meaningful considering that this is a GUI tool, not a CLI one. If you often find yourself looking into CLI dumps of a GUI tool then maybe the GUI is worth redesigning.

**Comment by PrincePepper** [comment]
Thanks a lot. Sorry for bother
