### ISSUE TITLE
v0 REPO has moved... https://github.com/dronecan/gui_tool and is now called DroneCan!

### ISSUE THREAD

**Issue by davidbuzz** [UAVCAN/gui_tool#55]
The README has incorrect info about the status of 'v0' , calling it 'legacy', and it would be more accurate to say that many in the community have decided to fork it elsewhere and carry on using v0 as it's well-proven and widely deployed.

New url: https://github.com/dronecan/gui_tool
New name: DroneCan

**Comment by pavel-kirienko** [comment]
Thanks, README updated with the link you specified.
